workflows:
  react_build:
    name: React App Build
    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build app
        script: |
          npm run build

    artifacts:
     - build/**/outputs/apk/**/*.apk                   # relative path for a project in root directory
     - subfolder_name/build/**/outputs/apk/**/*.apk 
      
    cache:
      paths:
        - node_modules

    triggers:
      - event: push
        branch:
          - main  # Change this to your main branch name

      # You can add additional triggers as needed

    publishing:
      email:
        recipients:
          - manimv1268@gmail.com  # Add your email here if you want to receive build status emails
