workflows:
  react_native_workflow:
    name: React Native Build and Test
    environment:
      flutter: latest
    scripts:
      - name: Install dependencies
        script: npm install

      - name: Build iOS
        script: |
          npm run build
          npm run ios
          npx react-native run-ios --configuration=release

      - name: Build Android
        script: |
          npm run android
          npx react-native run-android --variant=release

      - name: Run Tests
        script: |
          yarn test
          

      - name: yarn Starts
        script: |
          npm start
          yarn start    

      # - name: Archive Build Artifacts
      #   script: |
      #     # Archive build artifacts, e.g., APK, IPA, or other necessary files

      # Additional steps for deployment or notifications can be added here
      artifacts:
       - build/**/*
       - ios/build/*.ipa
       - android/app/build/outputs/**/*.apk

      publishing:
      email:
        recipients:
          - manimv1268@gmail.com   