workflows:
  react_native_workflow:
    name: React Native Build and Test
    max_build_duration: 120
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: npm install

      - name: Build iOS
        script: |
          cd ios/
          pod install
          xcodebuild clean -workspace Coffee_Shop_App.xcworkspace -scheme Coffee_Shop_App -configuration Release
          xcodebuild archive -workspace Coffee_Shop_App.xcworkspace -scheme Coffee_Shop_App -configuration Release -archivePath build/Coffee_Shop_App.xcarchive
          xcodebuild -exportArchive -archivePath build/rCoffee_Shop_App.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build/docker/ios
        #  npx docker run-ios --configuration=release
          npm run ios
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties" 
      - name: Build Android
        script: |
          cd android && chmod +x gradlew && ./gradlew assembleRelease
          cd .. && npx docker bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/

   
          cd android && ./gradlew assembleRelease
          npm run android
        #  npx docker run-android --variant=release

      # - name: Run Tests
      #   script: |
      #     cd __tests__
      #     yarn test
      - name: npm Starts
        script: |
          npm start
#          yarn start    

      # - name: Archive Build Artifacts
      #   script: |
      #     # Archive build artifacts, e.g., APK, IPA, or other necessary files

      # Additional steps for deployment or notifications can be added here
    artifacts:
      - build/**/*
      - ios/build/*.ipa
      - android/app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - manimv1268@gmail.com   