workflows:
  react_native_workflow:
    name: React Native Build and Test
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: npm install

      - name: Build iOS
        script: |
          cd ios/
          pod install
          xcodebuild clean -workspace reactapp.xcworkspace -scheme myreact -configuration Release
          xcodebuild archive -workspace reactapp.xcworkspace -scheme myreact -configuration Release -archivePath build/reactapp.xcarchive
          xcodebuild -exportArchive -archivePath build/reactapp.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build/Downloads/react

          npm run build
          #npm run ios
          npx react-native run-ios --configuration=release

      - name: Build Android
        script: |
          cd android && ./gradlew clean
          cd .. && npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/

   
          cd android && ./gradlew assembleRelease
          #npm run android
          npx react-native run-android --variant=release

      - name: Run Tests
        script: |
          yarn test
          

      - name: yarn Starts
        script: |
          npm start
          yarn start    

      # - name: Archive Build Artifacts
      #   script: |
      #     # Archive build artifacts, e.g., APK, IPA, or other necessary files

      # Additional steps for deployment or notifications can be added here
    artifacts:
      - build/**/*
      - ios/build/*.ipa
      - android/app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - manimv1268@gmail.com   